module PowerIQ
  module Resource
    autoload :Base, 'poweriq_client/resource/base'
    autoload :Aisle, 'poweriq_client/resource/aisle'
    autoload :AssetStrip, 'poweriq_client/resource/asset_strip'
    autoload :CircuitBreakerReading, 'poweriq_client/resource/circuit_breaker_reading'
    autoload :CircuitBreakerReadingsRollup, 'poweriq_client/resource/circuit_breaker_readings_rollup'
    autoload :DataCenter, 'poweriq_client/resource/data_center'
    autoload :Device, 'poweriq_client/resource/device'
    autoload :Event, 'poweriq_client/resource/event'
    autoload :Floor, 'poweriq_client/resource/floor'
    autoload :Job, 'poweriq_client/resource/job'
    autoload :JobMessage, 'poweriq_client/resource/job_message'
    autoload :LineReading, 'poweriq_client/resource/line_reading'
    autoload :LineReadingsRollup, 'poweriq_client/resource/line_readings_rollup'
    autoload :Outlet, 'poweriq_client/resource/outlet'
    autoload :OutletReading, 'poweriq_client/resource/outlet_reading'
    autoload :OutletReadingsRollup, 'poweriq_client/resource/outlet_readings_rollup'
    autoload :Pdu, 'poweriq_client/resource/pdu'
    autoload :Rack, 'poweriq_client/resource/rack'
    autoload :RackUnit, 'poweriq_client/resource/rack_unit'
    autoload :Room, 'poweriq_client/resource/room'
    autoload :Row, 'poweriq_client/resource/row'
    autoload :Sensor, 'poweriq_client/resource/sensor'
    autoload :SensorReading, 'poweriq_client/resource/sensor_reading'
    autoload :SensorReadingsRollup, 'poweriq_client/resource/sensor_readings_rollup'
    autoload :SystemInfo, 'poweriq_client/resource/system_info'
  end
end